package com.example.rag.dto;

import java.util.List;

/**
 * Document summary generated by the LLM.
 */
public record SummaryResponse(
        String shortSummary,
        String detailedSummary,
        List<String> keyPoints
) {
}
